version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: CommunicationSystem
      MYSQL_USER: evan
      MYSQL_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
