version: '3'
services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5003:5003"
    depends_on:
      - db