version: '3.8'
services:
  db:
    image: mariadb:latest
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - MYSQL_HOST=db
    ports:
      - "5003:5003"
    depends_on:
      - db
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_URI=http://localhost
    ports:
      - "3000:3000"
    depends_on:
      - backend