DROP DATABASE IF EXISTS CommunicationSystem;

CREATE DATABASE CommunicationSystem;

USE CommunicationSystem;

CREATE TABLE User (
    UserId INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL   
);

CREATE TABLE Channel (
    ChannelId INT AUTO_INCREMENT PRIMARY KEY,
    ChannelName VARCHAR(255) NOT NULL,
    ChannelJoinId VARCHAR(8) NOT NULL,
);

CREATE TABLE UserChannel (
    UserChannelId INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    ChannelId INT NOT NULL,
    CONSTRAINT FK_UserChannel_User FOREIGN KEY (UserId) REFERENCES User(UserId) ON DELETE CASCADE,
    CONSTRAINT FK_UserChannel_Channel FOREIGN KEY (ChannelId) REFERENCES Channel(ChannelId) ON DELETE CASCADE
);

CREATE TABLE Message (
    MessageId INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    ChannelId INT NOT NULL,
    Content VARCHAR(255) NOT NULL,
    SentAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES User(UserId) ON DELETE CASCADE,
    FOREIGN KEY (ChannelId) REFERENCES Channel(ChannelId) ON DELETE CASCADE
);